"""add note to messages

Revision ID: 901e8a30b3c7
Revises: 
Create Date: 2025-07-17 15:13:23.344787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901e8a30b3c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
